name: nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: "nix build"
    environment: cachix
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
      - name: "build dependencies"
        run: nix build .#cargoArtifacts -Lvv --no-update-lock-file
      - run: |
          nix build || nix build --substituters 'https://cache.nixos.org' --extra-substituters ''

  check:
    runs-on: ubuntu-latest
    name: "nix check"
    environment: cachix
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: kenji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
      - run: nix flake check
