name: nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: "nix build"
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - run: |
          nix build || nix build --substituters 'https://cache.nixos.org' --extra-substituters ''

  check:
    runs-on: ubuntu-latest
    name: "nix check"
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - run: nix flake check
